// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ll5IvOH0uTu0rgAam7knRr1KehPTrhk',
    appId: '1:965984278020:web:56cc5acfe4eebe5d3b0751',
    messagingSenderId: '965984278020',
    projectId: 'hehe2-b05f5',
    authDomain: 'hehe2-b05f5.firebaseapp.com',
    storageBucket: 'hehe2-b05f5.firebasestorage.app',
    measurementId: 'G-0KGXEBKLQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8WUrHlDQROA6J-aUebPmJrutisI1wRh0',
    appId: '1:965984278020:android:78e34ac13a830e833b0751',
    messagingSenderId: '965984278020',
    projectId: 'hehe2-b05f5',
    storageBucket: 'hehe2-b05f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlWzlVYIKs-7H0StWq1p_CEKdcwv4Q5XU',
    appId: '1:965984278020:ios:247cd564deaef3d43b0751',
    messagingSenderId: '965984278020',
    projectId: 'hehe2-b05f5',
    storageBucket: 'hehe2-b05f5.firebasestorage.app',
    iosBundleId: 'com.example.responsi2200016058',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlWzlVYIKs-7H0StWq1p_CEKdcwv4Q5XU',
    appId: '1:965984278020:ios:247cd564deaef3d43b0751',
    messagingSenderId: '965984278020',
    projectId: 'hehe2-b05f5',
    storageBucket: 'hehe2-b05f5.firebasestorage.app',
    iosBundleId: 'com.example.responsi2200016058',
  );
}
